services:
  openldap:
    build: ./
    container_name: openldap
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /etc/letsencrypt:/container/service/slapd/assets/certs/
    ports:
      - "389:389"
