services:
  openldap:
    build: ./
    environment:
      - LDAP_DOMAIN=${LDAP_DOMAIN:-cotak.gov}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD:-admin}
      - LDAP_SVC_PASSWORD=${LDAP_SVC_PASSWORD:-service}
    ports:
      - "${LDAP_PORT:-3389}:389"
