#!/bin/bash

set -euo pipefail

echo "Generating LDIF"
echo "Domain: ${LDAPDomain}"

ORG=$(echo "${LDAPDomain}" | sed 's/\..*$//')
TLD=$(echo "${LDAPDomain}" | sed 's/^.*\.//')

echo "ORG: ${ORG}"
echo "TLD: ${TLD}"

for filename in /container/templates/; do
    echo "Building ${filename}"

    sed -i "s/\$\{ORG\}/${ORG}/" "${filename}"
    sed -i "s/\$\{ORG\}/${TLD}/" "${filename}"

    cp "${filename}" "/container/service/slapd/assets/config/bootstrap/ldif/"
done

/container/tool/run
