#!/bin/bash

set -euo pipefail

echo "Generating LDIF"
echo "Domain: ${LDAP_DOMAIN}"

ORG="$(echo "${LDAP_DOMAIN}" | sed 's/\..*$//')"
TLD="$(echo "${LDAP_DOMAIN}" | sed 's/^.*\.//')"

echo "ORG: ${ORG}"
echo "TLD: ${TLD}"

SERVICE_PASSWORD="$(slappasswd -s ${LDAP_SVC_PASSWORD})"

for filename in /container/templates/*.ldif; do
    echo "Building ${filename}"

    sed -i "s/CUSTOM_ORG/${ORG}/" "${filename}"
    sed -i "s/CUSTOM_TLD/${TLD}/" "${filename}"
    sed -i "s/CUSTOM_SERVICE_PASSWORD/${SERVICE_PASSWORD}/" "${filename}"

    cp "${filename}" "/container/service/slapd/assets/config/bootstrap/ldif/"
done

/container/tool/run
