FROM ghcr.io/goauthentik/ldap:2025.8.1

LABEL org.opencontainers.image.source=https://github.com/dfpc-coe/auth-infra
LABEL org.opencontainers.image.description="Authentik server for TAK server auth via LDAP"
LABEL org.opencontainers.image.licenses=MIT
